service: serverlessSetup
provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  # vpc:
  #   securityGroupIds:
  #     - HERE_YOUR_SECURITY_GROUP
  #   subnetIds:
  #     - HERE_YOUR_SUBNET_1
  #     - HERE_YOUR_SUBNET_2
  #     - HERE_YOUR_SUBNET_3
  # environment:
  #   MYSQLHOST: 'xxxxx.rds.amazonaws.com'
  #   MYSQLPORT: 'xxx'
  #   MYSQLUSER: 'xxx'
  #   MYSQLPASS: 'xxxxx'
  #   MYSQLDATABASE: 'xxxx'
functions:
  hello:
    handler: src/api/handlers/hello.handler
    events:
      - http:
          path: serverlessSetup/hello
          method: get
  goodbye:
    handler: src/api/handlers/goodbye.handler
    events:
      - http:
          path: serverlessSetup/goodbye
          method: post
  question:
    handler: src/api/handlers/question.handler
    dependsOn: SNSQuestionEvent
    events:
      - sns:
          arn: !Ref SNSQuestionEvent
          topicName: hello-event
plugins:
  - serverless-plugin-typescript
  - serverless-offline
resources:
  Resources:
    SNSQuestionEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Question Event Topic
        TopicName: question-event
