service: serverlessSetup
provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
functions:
  hello:
    handler: src/api/handlers/hello.handler
    events:
      - http:
          path: serverlessSetup/hello
          method: get
  goodbye:
    handler: src/api/handlers/goodbye.handler
    events:
      - http:
          path: serverlessSetup/goodbye
          method: post
  question:
    handler: src/api/handlers/question.handler
    dependsOn: SNSQuestionEvent
    events:
      - sns:
          arn: !Ref SNSQuestionEvent
          topicName: hello-event
plugins:
  - serverless-plugin-typescript
  - serverless-offline
resources:
  Resources:
    SNSQuestionEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Question Event Topic
        TopicName: question-prod-event